include:
  - project: 'proton/fe/proton-config'
    ref: master
    file: '/_templates-ci/public.gitlab-ci.yml'

variables:
    APP_GIT: git@github.com:ProtonMail/proton-mail-settings.git
    NODE_OPTIONS: --max-old-space-size=4096
